name: Production Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: insurance-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: üì• Descargar c√≥digo
      uses: actions/checkout@v4

    - name: üîê Configurar Credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: üêç Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: üì¶ Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt


    - name: ü§ñ Entrenar Nuevo Modelo
      run: |
        # --- LIMPIEZA CR√çTICA ---
        rm -f mlflow.db
        rm -rf mlruns
        
        # Configuraci√≥n normal
        export PYTHONPATH=$PYTHONPATH:.
        python src/training/train.py

    - name: üîÑ Actualizar ID del Modelo en la API
      run: |
        NEW_RUN_ID=$(cat latest_run_id.txt)
        echo "Inyectando Run ID: $NEW_RUN_ID en main.py"
        sed -i "s/RUN_ID = \".*\"/RUN_ID = \"$NEW_RUN_ID\"/" src/app/main.py
        grep "RUN_ID =" src/app/main.py

    - name: üîê Login en AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: üê≥ Construir y Subir Imagen Docker
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $REGISTRY/$ECR_REPOSITORY:latest
        docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$ECR_REPOSITORY:latest
        
    - name: ‚úÖ √âxito
      run: echo "La imagen $IMAGE_TAG ha sido subida a ECR correctamente."